/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  LegalEntityTaxesApi,
  ApplicantTrackingSystemApi,
  EmployeeLegacyPerformTimeSchedulesApi,
  EmployeeCertificationsApi,
  EmployeeCustomFieldsApi,
  EmployeeDeductionsApi,
  EmployeeDirectDepositsApi,
  EmployeeDocumentsApi,
  EmployeeEarningsApi,
  EmployeeEmergencyContactApi,
  EmployeeI9VerificationApi,
  EmployeeOnboardingApi,
  EmployeePayRatesApi,
  EmployeePayScheduleApi,
  EmployeePayStubsApi,
  EmployeePayrollHoursApi,
  EmployeeTaxesApi,
  EmployeeTimeCardPunchesApi,
  EmployeeTimeOffAccrualsApi,
  EmployeesApi,
  EventsApi,
  GeneralLedgerApi,
  GeneralLedgerJobCostingApi,
  JobTitlesApi,
  LaborCategoriesApi,
  LaborCodesApi,
  LegalEntitiesApi,
  LegalEntityActivityTypesApi,
  LegalEntityCertificationsApi,
  LegalEntityDeductionsApi,
  LegalEntityDepartmentsApi,
  LegalEntityEarningsApi,
  LegalEntityJobTitlesApi,
  LegalEntityPayDataApi,
  LegalEntityPayGroupsApi,
  LegalEntityPayScheduleApi,
  LegalEntityPayrollProcessingDataApi,
  LegalEntityScheduleGroupsApi,
  LegalEntityServicesApi,
  LegalEntityStatusReasonApi,
  LegalEntityTimeDataApi,
  LegalEntityTimeOffTypesApi,
  LegalEntityWorkLocationsApi,
  LegalEntityWorkSitesApi,
  PersonsApi,
  TenantsApi,
  TimeOffRequestsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PaycorCustom } from "./client-custom";

export class Paycor extends PaycorCustom {
  readonly legalEntityTaxes: LegalEntityTaxesApi;
  readonly applicantTrackingSystem: ApplicantTrackingSystemApi;
  readonly employeeLegacyPerformTimeSchedules: EmployeeLegacyPerformTimeSchedulesApi;
  readonly employeeCertifications: EmployeeCertificationsApi;
  readonly employeeCustomFields: EmployeeCustomFieldsApi;
  readonly employeeDeductions: EmployeeDeductionsApi;
  readonly employeeDirectDeposits: EmployeeDirectDepositsApi;
  readonly employeeDocuments: EmployeeDocumentsApi;
  readonly employeeEarnings: EmployeeEarningsApi;
  readonly employeeEmergencyContact: EmployeeEmergencyContactApi;
  readonly employeeI9Verification: EmployeeI9VerificationApi;
  readonly employeeOnboarding: EmployeeOnboardingApi;
  readonly employeePayRates: EmployeePayRatesApi;
  readonly employeePaySchedule: EmployeePayScheduleApi;
  readonly employeePayStubs: EmployeePayStubsApi;
  readonly employeePayrollHours: EmployeePayrollHoursApi;
  readonly employeeTaxes: EmployeeTaxesApi;
  readonly employeeTimeCardPunches: EmployeeTimeCardPunchesApi;
  readonly employeeTimeOffAccruals: EmployeeTimeOffAccrualsApi;
  readonly employees: EmployeesApi;
  readonly events: EventsApi;
  readonly generalLedger: GeneralLedgerApi;
  readonly generalLedgerJobCosting: GeneralLedgerJobCostingApi;
  readonly jobTitles: JobTitlesApi;
  readonly laborCategories: LaborCategoriesApi;
  readonly laborCodes: LaborCodesApi;
  readonly legalEntities: LegalEntitiesApi;
  readonly legalEntityActivityTypes: LegalEntityActivityTypesApi;
  readonly legalEntityCertifications: LegalEntityCertificationsApi;
  readonly legalEntityDeductions: LegalEntityDeductionsApi;
  readonly legalEntityDepartments: LegalEntityDepartmentsApi;
  readonly legalEntityEarnings: LegalEntityEarningsApi;
  readonly legalEntityJobTitles: LegalEntityJobTitlesApi;
  readonly legalEntityPayData: LegalEntityPayDataApi;
  readonly legalEntityPayGroups: LegalEntityPayGroupsApi;
  readonly legalEntityPaySchedule: LegalEntityPayScheduleApi;
  readonly legalEntityPayrollProcessingData: LegalEntityPayrollProcessingDataApi;
  readonly legalEntityScheduleGroups: LegalEntityScheduleGroupsApi;
  readonly legalEntityServices: LegalEntityServicesApi;
  readonly legalEntityStatusReason: LegalEntityStatusReasonApi;
  readonly legalEntityTimeData: LegalEntityTimeDataApi;
  readonly legalEntityTimeOffTypes: LegalEntityTimeOffTypesApi;
  readonly legalEntityWorkLocations: LegalEntityWorkLocationsApi;
  readonly legalEntityWorkSites: LegalEntityWorkSitesApi;
  readonly persons: PersonsApi;
  readonly tenants: TenantsApi;
  readonly timeOffRequests: TimeOffRequestsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.legalEntityTaxes = new LegalEntityTaxesApi(configuration);
    this.applicantTrackingSystem = new ApplicantTrackingSystemApi(configuration);
    this.employeeLegacyPerformTimeSchedules = new EmployeeLegacyPerformTimeSchedulesApi(configuration);
    this.employeeCertifications = new EmployeeCertificationsApi(configuration);
    this.employeeCustomFields = new EmployeeCustomFieldsApi(configuration);
    this.employeeDeductions = new EmployeeDeductionsApi(configuration);
    this.employeeDirectDeposits = new EmployeeDirectDepositsApi(configuration);
    this.employeeDocuments = new EmployeeDocumentsApi(configuration);
    this.employeeEarnings = new EmployeeEarningsApi(configuration);
    this.employeeEmergencyContact = new EmployeeEmergencyContactApi(configuration);
    this.employeeI9Verification = new EmployeeI9VerificationApi(configuration);
    this.employeeOnboarding = new EmployeeOnboardingApi(configuration);
    this.employeePayRates = new EmployeePayRatesApi(configuration);
    this.employeePaySchedule = new EmployeePayScheduleApi(configuration);
    this.employeePayStubs = new EmployeePayStubsApi(configuration);
    this.employeePayrollHours = new EmployeePayrollHoursApi(configuration);
    this.employeeTaxes = new EmployeeTaxesApi(configuration);
    this.employeeTimeCardPunches = new EmployeeTimeCardPunchesApi(configuration);
    this.employeeTimeOffAccruals = new EmployeeTimeOffAccrualsApi(configuration);
    this.employees = new EmployeesApi(configuration);
    this.events = new EventsApi(configuration);
    this.generalLedger = new GeneralLedgerApi(configuration);
    this.generalLedgerJobCosting = new GeneralLedgerJobCostingApi(configuration);
    this.jobTitles = new JobTitlesApi(configuration);
    this.laborCategories = new LaborCategoriesApi(configuration);
    this.laborCodes = new LaborCodesApi(configuration);
    this.legalEntities = new LegalEntitiesApi(configuration);
    this.legalEntityActivityTypes = new LegalEntityActivityTypesApi(configuration);
    this.legalEntityCertifications = new LegalEntityCertificationsApi(configuration);
    this.legalEntityDeductions = new LegalEntityDeductionsApi(configuration);
    this.legalEntityDepartments = new LegalEntityDepartmentsApi(configuration);
    this.legalEntityEarnings = new LegalEntityEarningsApi(configuration);
    this.legalEntityJobTitles = new LegalEntityJobTitlesApi(configuration);
    this.legalEntityPayData = new LegalEntityPayDataApi(configuration);
    this.legalEntityPayGroups = new LegalEntityPayGroupsApi(configuration);
    this.legalEntityPaySchedule = new LegalEntityPayScheduleApi(configuration);
    this.legalEntityPayrollProcessingData = new LegalEntityPayrollProcessingDataApi(configuration);
    this.legalEntityScheduleGroups = new LegalEntityScheduleGroupsApi(configuration);
    this.legalEntityServices = new LegalEntityServicesApi(configuration);
    this.legalEntityStatusReason = new LegalEntityStatusReasonApi(configuration);
    this.legalEntityTimeData = new LegalEntityTimeDataApi(configuration);
    this.legalEntityTimeOffTypes = new LegalEntityTimeOffTypesApi(configuration);
    this.legalEntityWorkLocations = new LegalEntityWorkLocationsApi(configuration);
    this.legalEntityWorkSites = new LegalEntityWorkSitesApi(configuration);
    this.persons = new PersonsApi(configuration);
    this.tenants = new TenantsApi(configuration);
    this.timeOffRequests = new TimeOffRequestsApi(configuration);
  }

}
