/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ATSAccount } from '../models';
// @ts-ignore
import { Includes } from '../models';
// @ts-ignore
import { Includes2 } from '../models';
// @ts-ignore
import { Job } from '../models';
// @ts-ignore
import { JobStatus } from '../models';
// @ts-ignore
import { PagedResultOfJob } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ApplicantTrackingSystemApi - axios parameter creator
 * @export
 */
export const ApplicantTrackingSystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Data Access: View ATS Account jobs by ATS Account ID
         * @summary Get a list of ATS Account jobs for ATS Account Id
         * @param {number} legalEntityId Paycor Legal Entity ID of the legal entity for which you want to get the ATS account jobs
         * @param {string} atsAccountId ATS account ID of for which you want to get the ATS account jobs
         * @param {Array<Includes>} [include] Options to include more data: All, Hiring managers, Recruiters, Team members, Executives
         * @param {boolean} [postedToCareers] Option to filter jobs based on if they are posted to the careers page
         * @param {JobStatus} [status] Option to filter jobs by status
         * @param {string} [continuationToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountJobs: async (legalEntityId: number, atsAccountId: string, include?: Array<Includes>, postedToCareers?: boolean, status?: JobStatus, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('getAccountJobs', 'legalEntityId', legalEntityId)
            // verify required parameter 'atsAccountId' is not null or undefined
            assertParamExists('getAccountJobs', 'atsAccountId', atsAccountId)
            const localVarPath = `/v1/legalEntities/{legalEntityId}/ats/{atsAccountId}/jobs`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)))
                .replace(`{${"atsAccountId"}}`, encodeURIComponent(String(atsAccountId !== undefined ? atsAccountId : `-atsAccountId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (include) {
                localVarQueryParameter['include'] = include;
            }

            if (postedToCareers !== undefined) {
                localVarQueryParameter['postedToCareers'] = postedToCareers;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalEntities/{legalEntityId}/ats/{atsAccountId}/jobs',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View ATS Account Job by ATS Job Id
         * @summary Get an ATS Account Job for ATS Account Id
         * @param {number} legalEntityId Paycor Legal Entity ID of the legal entity for which you want to get the ATS account job
         * @param {string} atsAccountId ATS account ID of for which you want to get the ATS account job
         * @param {string} atsJobId ATS Job ID
         * @param {Array<Includes2>} [include] Options to include more data: All, Hiring managers, Recruiters, Team members, Executives
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobByJobId: async (legalEntityId: number, atsAccountId: string, atsJobId: string, include?: Array<Includes2>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('getJobByJobId', 'legalEntityId', legalEntityId)
            // verify required parameter 'atsAccountId' is not null or undefined
            assertParamExists('getJobByJobId', 'atsAccountId', atsAccountId)
            // verify required parameter 'atsJobId' is not null or undefined
            assertParamExists('getJobByJobId', 'atsJobId', atsJobId)
            const localVarPath = `/v1/legalEntities/{legalEntityId}/ats/{atsAccountId}/jobs/{atsJobId}`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)))
                .replace(`{${"atsAccountId"}}`, encodeURIComponent(String(atsAccountId !== undefined ? atsAccountId : `-atsAccountId-`)))
                .replace(`{${"atsJobId"}}`, encodeURIComponent(String(atsJobId !== undefined ? atsJobId : `-atsJobId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (include) {
                localVarQueryParameter['include'] = include;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalEntities/{legalEntityId}/ats/{atsAccountId}/jobs/{atsJobId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View ATS Accounts By Legal Entity Id
         * @summary Get a list of ATS Accounts for Legal Entity
         * @param {number} legalEntityId Paycor Legal Entity ID of the legal entity for which you want to get the ATS accounts
         * @param {string} [continuationToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAtsAccountsByLegalEntity: async (legalEntityId: number, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('listAtsAccountsByLegalEntity', 'legalEntityId', legalEntityId)
            const localVarPath = `/v1/legalEntities/{legalEntityId}/ats/accounts`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalEntities/{legalEntityId}/ats/accounts',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApplicantTrackingSystemApi - functional programming interface
 * @export
 */
export const ApplicantTrackingSystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApplicantTrackingSystemApiAxiosParamCreator(configuration)
    return {
        /**
         * Data Access: View ATS Account jobs by ATS Account ID
         * @summary Get a list of ATS Account jobs for ATS Account Id
         * @param {ApplicantTrackingSystemApiGetAccountJobsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountJobs(requestParameters: ApplicantTrackingSystemApiGetAccountJobsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfJob>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccountJobs(requestParameters.legalEntityId, requestParameters.atsAccountId, requestParameters.include, requestParameters.postedToCareers, requestParameters.status, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View ATS Account Job by ATS Job Id
         * @summary Get an ATS Account Job for ATS Account Id
         * @param {ApplicantTrackingSystemApiGetJobByJobIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobByJobId(requestParameters: ApplicantTrackingSystemApiGetJobByJobIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Job>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobByJobId(requestParameters.legalEntityId, requestParameters.atsAccountId, requestParameters.atsJobId, requestParameters.include, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View ATS Accounts By Legal Entity Id
         * @summary Get a list of ATS Accounts for Legal Entity
         * @param {ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAtsAccountsByLegalEntity(requestParameters: ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ATSAccount>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAtsAccountsByLegalEntity(requestParameters.legalEntityId, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ApplicantTrackingSystemApi - factory interface
 * @export
 */
export const ApplicantTrackingSystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApplicantTrackingSystemApiFp(configuration)
    return {
        /**
         * Data Access: View ATS Account jobs by ATS Account ID
         * @summary Get a list of ATS Account jobs for ATS Account Id
         * @param {ApplicantTrackingSystemApiGetAccountJobsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountJobs(requestParameters: ApplicantTrackingSystemApiGetAccountJobsRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfJob> {
            return localVarFp.getAccountJobs(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View ATS Account Job by ATS Job Id
         * @summary Get an ATS Account Job for ATS Account Id
         * @param {ApplicantTrackingSystemApiGetJobByJobIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobByJobId(requestParameters: ApplicantTrackingSystemApiGetJobByJobIdRequest, options?: AxiosRequestConfig): AxiosPromise<Job> {
            return localVarFp.getJobByJobId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View ATS Accounts By Legal Entity Id
         * @summary Get a list of ATS Accounts for Legal Entity
         * @param {ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAtsAccountsByLegalEntity(requestParameters: ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest, options?: AxiosRequestConfig): AxiosPromise<ATSAccount> {
            return localVarFp.listAtsAccountsByLegalEntity(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAccountJobs operation in ApplicantTrackingSystemApi.
 * @export
 * @interface ApplicantTrackingSystemApiGetAccountJobsRequest
 */
export type ApplicantTrackingSystemApiGetAccountJobsRequest = {
    
    /**
    * Paycor Legal Entity ID of the legal entity for which you want to get the ATS account jobs
    * @type {number}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly legalEntityId: number
    
    /**
    * ATS account ID of for which you want to get the ATS account jobs
    * @type {string}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly atsAccountId: string
    
    /**
    * Options to include more data: All, Hiring managers, Recruiters, Team members, Executives
    * @type {Array<Includes>}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly include?: Array<Includes>
    
    /**
    * Option to filter jobs based on if they are posted to the careers page
    * @type {boolean}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly postedToCareers?: boolean
    
    /**
    * Option to filter jobs by status
    * @type {JobStatus}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly status?: JobStatus
    
    /**
    * 
    * @type {string}
    * @memberof ApplicantTrackingSystemApiGetAccountJobs
    */
    readonly continuationToken?: string
    
}

/**
 * Request parameters for getJobByJobId operation in ApplicantTrackingSystemApi.
 * @export
 * @interface ApplicantTrackingSystemApiGetJobByJobIdRequest
 */
export type ApplicantTrackingSystemApiGetJobByJobIdRequest = {
    
    /**
    * Paycor Legal Entity ID of the legal entity for which you want to get the ATS account job
    * @type {number}
    * @memberof ApplicantTrackingSystemApiGetJobByJobId
    */
    readonly legalEntityId: number
    
    /**
    * ATS account ID of for which you want to get the ATS account job
    * @type {string}
    * @memberof ApplicantTrackingSystemApiGetJobByJobId
    */
    readonly atsAccountId: string
    
    /**
    * ATS Job ID
    * @type {string}
    * @memberof ApplicantTrackingSystemApiGetJobByJobId
    */
    readonly atsJobId: string
    
    /**
    * Options to include more data: All, Hiring managers, Recruiters, Team members, Executives
    * @type {Array<Includes2>}
    * @memberof ApplicantTrackingSystemApiGetJobByJobId
    */
    readonly include?: Array<Includes2>
    
}

/**
 * Request parameters for listAtsAccountsByLegalEntity operation in ApplicantTrackingSystemApi.
 * @export
 * @interface ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest
 */
export type ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest = {
    
    /**
    * Paycor Legal Entity ID of the legal entity for which you want to get the ATS accounts
    * @type {number}
    * @memberof ApplicantTrackingSystemApiListAtsAccountsByLegalEntity
    */
    readonly legalEntityId: number
    
    /**
    * 
    * @type {string}
    * @memberof ApplicantTrackingSystemApiListAtsAccountsByLegalEntity
    */
    readonly continuationToken?: string
    
}

/**
 * ApplicantTrackingSystemApiGenerated - object-oriented interface
 * @export
 * @class ApplicantTrackingSystemApiGenerated
 * @extends {BaseAPI}
 */
export class ApplicantTrackingSystemApiGenerated extends BaseAPI {
    /**
     * Data Access: View ATS Account jobs by ATS Account ID
     * @summary Get a list of ATS Account jobs for ATS Account Id
     * @param {ApplicantTrackingSystemApiGetAccountJobsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantTrackingSystemApiGenerated
     */
    public getAccountJobs(requestParameters: ApplicantTrackingSystemApiGetAccountJobsRequest, options?: AxiosRequestConfig) {
        return ApplicantTrackingSystemApiFp(this.configuration).getAccountJobs(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View ATS Account Job by ATS Job Id
     * @summary Get an ATS Account Job for ATS Account Id
     * @param {ApplicantTrackingSystemApiGetJobByJobIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantTrackingSystemApiGenerated
     */
    public getJobByJobId(requestParameters: ApplicantTrackingSystemApiGetJobByJobIdRequest, options?: AxiosRequestConfig) {
        return ApplicantTrackingSystemApiFp(this.configuration).getJobByJobId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View ATS Accounts By Legal Entity Id
     * @summary Get a list of ATS Accounts for Legal Entity
     * @param {ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApplicantTrackingSystemApiGenerated
     */
    public listAtsAccountsByLegalEntity(requestParameters: ApplicantTrackingSystemApiListAtsAccountsByLegalEntityRequest, options?: AxiosRequestConfig) {
        return ApplicantTrackingSystemApiFp(this.configuration).listAtsAccountsByLegalEntity(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
