/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateOrUpdateResponse } from '../models';
// @ts-ignore
import { EmployeeEarning } from '../models';
// @ts-ignore
import { EmployeeEarning2 } from '../models';
// @ts-ignore
import { EmployeeEarning3 } from '../models';
// @ts-ignore
import { EmployeeEarningAmount } from '../models';
// @ts-ignore
import { IncludeInPay } from '../models';
// @ts-ignore
import { Includes5 } from '../models';
// @ts-ignore
import { Includes6 } from '../models';
// @ts-ignore
import { PagedResultOfEmployeeEarning } from '../models';
// @ts-ignore
import { PayFrequency } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeEarningsApi - axios parameter creator
 * @export
 */
export const EmployeeEarningsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Data Access: Add Employee Earning
         * @summary Add Earning to Employee
         * @param {string} employeeId ID of an Employee for whom you want to add an Earning
         * @param {EmployeeEarning2} employeeEarning2 Employee Earning object to insert
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewEarning: async (employeeId: string, employeeEarning2: EmployeeEarning2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addNewEarning', 'employeeId', employeeId)
            // verify required parameter 'employeeEarning2' is not null or undefined
            assertParamExists('addNewEarning', 'employeeEarning2', employeeEarning2)
            const localVarPath = `/v1/employees/{employeeId}/earnings`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeEarning2,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/earnings',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeEarning2, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View Employee Earning Information
         * @summary Get Employee Earning by EmployeeID and EmployeeEarningID
         * @param {string} employeeId ID of an Employee for whom you want to get the Earning
         * @param {string} employeeEarningId ID of an Employee Earning you want to get
         * @param {Array<Includes5>} [include] Options to include more data: All, AmountData  Data Access required  AmountData &#x3D; View Employee Earning Amounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeAndEarning: async (employeeId: string, employeeEarningId: string, include?: Array<Includes5>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getByEmployeeAndEarning', 'employeeId', employeeId)
            // verify required parameter 'employeeEarningId' is not null or undefined
            assertParamExists('getByEmployeeAndEarning', 'employeeEarningId', employeeEarningId)
            const localVarPath = `/v1/employees/{employeeId}/earnings/{employeeEarningId}`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)))
                .replace(`{${"employeeEarningId"}}`, encodeURIComponent(String(employeeEarningId !== undefined ? employeeEarningId : `-employeeEarningId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (include) {
                localVarQueryParameter['include'] = include;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/earnings/{employeeEarningId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View Employee Earnings Information
         * @summary Get Employee Earnings by EmployeeID
         * @param {string} employeeId ID of an Employee for whom you want to get the Earnings
         * @param {Array<Includes6>} [include] Options to include more data: All, AmountData  Data Access required  AmountData &#x3D; View Employee Earnings Amounts
         * @param {string} [continuationToken] Token to get the next set of Employee Earnings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeId: async (employeeId: string, include?: Array<Includes6>, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getByEmployeeId', 'employeeId', employeeId)
            const localVarPath = `/v1/employees/{employeeId}/earnings`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (include) {
                localVarQueryParameter['include'] = include;
            }

            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/earnings',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: Update Employee Earning
         * @summary Update Employee Earning
         * @param {string} employeeId ID of an Employee that has the Earning you wish to update
         * @param {EmployeeEarning3} employeeEarning3 Employee Earning object with updated fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateData: async (employeeId: string, employeeEarning3: EmployeeEarning3, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('updateData', 'employeeId', employeeId)
            // verify required parameter 'employeeEarning3' is not null or undefined
            assertParamExists('updateData', 'employeeEarning3', employeeEarning3)
            const localVarPath = `/v1/employees/{employeeId}/earnings`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeEarning3,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/earnings',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeEarning3, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeEarningsApi - functional programming interface
 * @export
 */
export const EmployeeEarningsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeEarningsApiAxiosParamCreator(configuration)
    return {
        /**
         * Data Access: Add Employee Earning
         * @summary Add Earning to Employee
         * @param {EmployeeEarningsApiAddNewEarningRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewEarning(requestParameters: EmployeeEarningsApiAddNewEarningRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const employeeEarning2: EmployeeEarning2 = {
                Code: requestParameters.Code,
                Frequency: requestParameters.Frequency,
                SequenceNumber: requestParameters.SequenceNumber,
                IncludeInPay: requestParameters.IncludeInPay,
                OnHold: requestParameters.OnHold,
                AmountData: requestParameters.AmountData
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewEarning(requestParameters.employeeId, employeeEarning2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View Employee Earning Information
         * @summary Get Employee Earning by EmployeeID and EmployeeEarningID
         * @param {EmployeeEarningsApiGetByEmployeeAndEarningRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByEmployeeAndEarning(requestParameters: EmployeeEarningsApiGetByEmployeeAndEarningRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeEarning>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByEmployeeAndEarning(requestParameters.employeeId, requestParameters.employeeEarningId, requestParameters.include, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View Employee Earnings Information
         * @summary Get Employee Earnings by EmployeeID
         * @param {EmployeeEarningsApiGetByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByEmployeeId(requestParameters: EmployeeEarningsApiGetByEmployeeIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfEmployeeEarning>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByEmployeeId(requestParameters.employeeId, requestParameters.include, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: Update Employee Earning
         * @summary Update Employee Earning
         * @param {EmployeeEarningsApiUpdateDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateData(requestParameters: EmployeeEarningsApiUpdateDataRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const employeeEarning3: EmployeeEarning3 = {
                Id: requestParameters.Id,
                Code: requestParameters.Code,
                Frequency: requestParameters.Frequency,
                SequenceNumber: requestParameters.SequenceNumber,
                IncludeInPay: requestParameters.IncludeInPay,
                OnHold: requestParameters.OnHold,
                AmountData: requestParameters.AmountData
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateData(requestParameters.employeeId, employeeEarning3, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeEarningsApi - factory interface
 * @export
 */
export const EmployeeEarningsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeEarningsApiFp(configuration)
    return {
        /**
         * Data Access: Add Employee Earning
         * @summary Add Earning to Employee
         * @param {EmployeeEarningsApiAddNewEarningRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewEarning(requestParameters: EmployeeEarningsApiAddNewEarningRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.addNewEarning(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View Employee Earning Information
         * @summary Get Employee Earning by EmployeeID and EmployeeEarningID
         * @param {EmployeeEarningsApiGetByEmployeeAndEarningRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeAndEarning(requestParameters: EmployeeEarningsApiGetByEmployeeAndEarningRequest, options?: AxiosRequestConfig): AxiosPromise<EmployeeEarning> {
            return localVarFp.getByEmployeeAndEarning(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View Employee Earnings Information
         * @summary Get Employee Earnings by EmployeeID
         * @param {EmployeeEarningsApiGetByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeId(requestParameters: EmployeeEarningsApiGetByEmployeeIdRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfEmployeeEarning> {
            return localVarFp.getByEmployeeId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: Update Employee Earning
         * @summary Update Employee Earning
         * @param {EmployeeEarningsApiUpdateDataRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateData(requestParameters: EmployeeEarningsApiUpdateDataRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.updateData(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addNewEarning operation in EmployeeEarningsApi.
 * @export
 * @interface EmployeeEarningsApiAddNewEarningRequest
 */
export type EmployeeEarningsApiAddNewEarningRequest = {
    
    /**
    * ID of an Employee for whom you want to add an Earning
    * @type {string}
    * @memberof EmployeeEarningsApiAddNewEarning
    */
    readonly employeeId: string
    
} & EmployeeEarning2

/**
 * Request parameters for getByEmployeeAndEarning operation in EmployeeEarningsApi.
 * @export
 * @interface EmployeeEarningsApiGetByEmployeeAndEarningRequest
 */
export type EmployeeEarningsApiGetByEmployeeAndEarningRequest = {
    
    /**
    * ID of an Employee for whom you want to get the Earning
    * @type {string}
    * @memberof EmployeeEarningsApiGetByEmployeeAndEarning
    */
    readonly employeeId: string
    
    /**
    * ID of an Employee Earning you want to get
    * @type {string}
    * @memberof EmployeeEarningsApiGetByEmployeeAndEarning
    */
    readonly employeeEarningId: string
    
    /**
    * Options to include more data: All, AmountData  Data Access required  AmountData = View Employee Earning Amounts
    * @type {Array<Includes5>}
    * @memberof EmployeeEarningsApiGetByEmployeeAndEarning
    */
    readonly include?: Array<Includes5>
    
}

/**
 * Request parameters for getByEmployeeId operation in EmployeeEarningsApi.
 * @export
 * @interface EmployeeEarningsApiGetByEmployeeIdRequest
 */
export type EmployeeEarningsApiGetByEmployeeIdRequest = {
    
    /**
    * ID of an Employee for whom you want to get the Earnings
    * @type {string}
    * @memberof EmployeeEarningsApiGetByEmployeeId
    */
    readonly employeeId: string
    
    /**
    * Options to include more data: All, AmountData  Data Access required  AmountData = View Employee Earnings Amounts
    * @type {Array<Includes6>}
    * @memberof EmployeeEarningsApiGetByEmployeeId
    */
    readonly include?: Array<Includes6>
    
    /**
    * Token to get the next set of Employee Earnings
    * @type {string}
    * @memberof EmployeeEarningsApiGetByEmployeeId
    */
    readonly continuationToken?: string
    
}

/**
 * Request parameters for updateData operation in EmployeeEarningsApi.
 * @export
 * @interface EmployeeEarningsApiUpdateDataRequest
 */
export type EmployeeEarningsApiUpdateDataRequest = {
    
    /**
    * ID of an Employee that has the Earning you wish to update
    * @type {string}
    * @memberof EmployeeEarningsApiUpdateData
    */
    readonly employeeId: string
    
} & EmployeeEarning3

/**
 * EmployeeEarningsApiGenerated - object-oriented interface
 * @export
 * @class EmployeeEarningsApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeEarningsApiGenerated extends BaseAPI {
    /**
     * Data Access: Add Employee Earning
     * @summary Add Earning to Employee
     * @param {EmployeeEarningsApiAddNewEarningRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeEarningsApiGenerated
     */
    public addNewEarning(requestParameters: EmployeeEarningsApiAddNewEarningRequest, options?: AxiosRequestConfig) {
        return EmployeeEarningsApiFp(this.configuration).addNewEarning(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View Employee Earning Information
     * @summary Get Employee Earning by EmployeeID and EmployeeEarningID
     * @param {EmployeeEarningsApiGetByEmployeeAndEarningRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeEarningsApiGenerated
     */
    public getByEmployeeAndEarning(requestParameters: EmployeeEarningsApiGetByEmployeeAndEarningRequest, options?: AxiosRequestConfig) {
        return EmployeeEarningsApiFp(this.configuration).getByEmployeeAndEarning(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View Employee Earnings Information
     * @summary Get Employee Earnings by EmployeeID
     * @param {EmployeeEarningsApiGetByEmployeeIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeEarningsApiGenerated
     */
    public getByEmployeeId(requestParameters: EmployeeEarningsApiGetByEmployeeIdRequest, options?: AxiosRequestConfig) {
        return EmployeeEarningsApiFp(this.configuration).getByEmployeeId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: Update Employee Earning
     * @summary Update Employee Earning
     * @param {EmployeeEarningsApiUpdateDataRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeEarningsApiGenerated
     */
    public updateData(requestParameters: EmployeeEarningsApiUpdateDataRequest, options?: AxiosRequestConfig) {
        return EmployeeEarningsApiFp(this.configuration).updateData(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
