/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Certification } from '../models';
// @ts-ignore
import { CreateOrUpdateResponse } from '../models';
// @ts-ignore
import { EmployeeCertification2 } from '../models';
// @ts-ignore
import { PagedResultOfEmployeeCertification } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeCertificationsApi - axios parameter creator
 * @export
 */
export const EmployeeCertificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Data Access: Create and Update Certification
         * @summary Add Employee Certification
         * @param {string} employeeId ID of an Employee for whom you want to add the certification
         * @param {Certification} certification Certification object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewCertification: async (employeeId: string, certification: Certification, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addNewCertification', 'employeeId', employeeId)
            // verify required parameter 'certification' is not null or undefined
            assertParamExists('addNewCertification', 'certification', certification)
            const localVarPath = `/v1/employees/{employeeId}/certifications`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: certification,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/certifications',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(certification, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View Certification Information for Employee
         * @summary Get a list of Employee Certifications for an employee
         * @param {string} employeeId ID of the employee for which you want to get the certifications
         * @param {string} [continuationToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByEmployeeId: async (employeeId: string, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('listByEmployeeId', 'employeeId', employeeId)
            const localVarPath = `/v1/employees/{employeeId}/certifications`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/certifications',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: Create and Update Certification
         * @summary Update Employee Certification
         * @param {string} employeeId ID of the employee for which you want to update the certifications
         * @param {EmployeeCertification2} employeeCertification2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCertification: async (employeeId: string, employeeCertification2: EmployeeCertification2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('updateCertification', 'employeeId', employeeId)
            // verify required parameter 'employeeCertification2' is not null or undefined
            assertParamExists('updateCertification', 'employeeCertification2', employeeCertification2)
            const localVarPath = `/v1/employees/{employeeId}/certifications`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeCertification2,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/certifications',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeCertification2, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeCertificationsApi - functional programming interface
 * @export
 */
export const EmployeeCertificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeCertificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Data Access: Create and Update Certification
         * @summary Add Employee Certification
         * @param {EmployeeCertificationsApiAddNewCertificationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewCertification(requestParameters: EmployeeCertificationsApiAddNewCertificationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const certification: Certification = {
                EffectiveDate: requestParameters.EffectiveDate,
                ExpirationDate: requestParameters.ExpirationDate,
                CertificationName: requestParameters.CertificationName,
                CertificationNumber: requestParameters.CertificationNumber,
                CertificationOrganizationName: requestParameters.CertificationOrganizationName,
                Notes: requestParameters.Notes
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewCertification(requestParameters.employeeId, certification, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View Certification Information for Employee
         * @summary Get a list of Employee Certifications for an employee
         * @param {EmployeeCertificationsApiListByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listByEmployeeId(requestParameters: EmployeeCertificationsApiListByEmployeeIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfEmployeeCertification>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listByEmployeeId(requestParameters.employeeId, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: Create and Update Certification
         * @summary Update Employee Certification
         * @param {EmployeeCertificationsApiUpdateCertificationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCertification(requestParameters: EmployeeCertificationsApiUpdateCertificationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const employeeCertification2: EmployeeCertification2 = {
                CertificationNumber: requestParameters.CertificationNumber,
                EmployeeCertificationId: requestParameters.EmployeeCertificationId,
                EffectiveDate: requestParameters.EffectiveDate,
                ExpirationDate: requestParameters.ExpirationDate,
                Notes: requestParameters.Notes
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCertification(requestParameters.employeeId, employeeCertification2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeCertificationsApi - factory interface
 * @export
 */
export const EmployeeCertificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeCertificationsApiFp(configuration)
    return {
        /**
         * Data Access: Create and Update Certification
         * @summary Add Employee Certification
         * @param {EmployeeCertificationsApiAddNewCertificationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewCertification(requestParameters: EmployeeCertificationsApiAddNewCertificationRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.addNewCertification(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View Certification Information for Employee
         * @summary Get a list of Employee Certifications for an employee
         * @param {EmployeeCertificationsApiListByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByEmployeeId(requestParameters: EmployeeCertificationsApiListByEmployeeIdRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfEmployeeCertification> {
            return localVarFp.listByEmployeeId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: Create and Update Certification
         * @summary Update Employee Certification
         * @param {EmployeeCertificationsApiUpdateCertificationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCertification(requestParameters: EmployeeCertificationsApiUpdateCertificationRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.updateCertification(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addNewCertification operation in EmployeeCertificationsApi.
 * @export
 * @interface EmployeeCertificationsApiAddNewCertificationRequest
 */
export type EmployeeCertificationsApiAddNewCertificationRequest = {
    
    /**
    * ID of an Employee for whom you want to add the certification
    * @type {string}
    * @memberof EmployeeCertificationsApiAddNewCertification
    */
    readonly employeeId: string
    
} & Certification

/**
 * Request parameters for listByEmployeeId operation in EmployeeCertificationsApi.
 * @export
 * @interface EmployeeCertificationsApiListByEmployeeIdRequest
 */
export type EmployeeCertificationsApiListByEmployeeIdRequest = {
    
    /**
    * ID of the employee for which you want to get the certifications
    * @type {string}
    * @memberof EmployeeCertificationsApiListByEmployeeId
    */
    readonly employeeId: string
    
    /**
    * 
    * @type {string}
    * @memberof EmployeeCertificationsApiListByEmployeeId
    */
    readonly continuationToken?: string
    
}

/**
 * Request parameters for updateCertification operation in EmployeeCertificationsApi.
 * @export
 * @interface EmployeeCertificationsApiUpdateCertificationRequest
 */
export type EmployeeCertificationsApiUpdateCertificationRequest = {
    
    /**
    * ID of the employee for which you want to update the certifications
    * @type {string}
    * @memberof EmployeeCertificationsApiUpdateCertification
    */
    readonly employeeId: string
    
} & EmployeeCertification2

/**
 * EmployeeCertificationsApiGenerated - object-oriented interface
 * @export
 * @class EmployeeCertificationsApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeCertificationsApiGenerated extends BaseAPI {
    /**
     * Data Access: Create and Update Certification
     * @summary Add Employee Certification
     * @param {EmployeeCertificationsApiAddNewCertificationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeCertificationsApiGenerated
     */
    public addNewCertification(requestParameters: EmployeeCertificationsApiAddNewCertificationRequest, options?: AxiosRequestConfig) {
        return EmployeeCertificationsApiFp(this.configuration).addNewCertification(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View Certification Information for Employee
     * @summary Get a list of Employee Certifications for an employee
     * @param {EmployeeCertificationsApiListByEmployeeIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeCertificationsApiGenerated
     */
    public listByEmployeeId(requestParameters: EmployeeCertificationsApiListByEmployeeIdRequest, options?: AxiosRequestConfig) {
        return EmployeeCertificationsApiFp(this.configuration).listByEmployeeId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: Create and Update Certification
     * @summary Update Employee Certification
     * @param {EmployeeCertificationsApiUpdateCertificationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeCertificationsApiGenerated
     */
    public updateCertification(requestParameters: EmployeeCertificationsApiUpdateCertificationRequest, options?: AxiosRequestConfig) {
        return EmployeeCertificationsApiFp(this.configuration).updateCertification(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
