/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateOrUpdateResponse } from '../models';
// @ts-ignore
import { EmployeePayRate2 } from '../models';
// @ts-ignore
import { EmployeePayRate3 } from '../models';
// @ts-ignore
import { PagedResultOfEmployeePayRate } from '../models';
// @ts-ignore
import { PayType } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeePayRatesApi - axios parameter creator
 * @export
 */
export const EmployeePayRatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This immediately creates a new payrate related to an Employee in Paycor\'s system. There is no way to undo or reverse this operation.   Data Access: Create Employee PayRates Sequence numbers must be consecutive and unique
         * @summary Add Payrate to Employee
         * @param {string} employeeId ID of the Employee you wish to create the payrate for
         * @param {EmployeePayRate2} employeePayRate2 Create Payrate model
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewRate: async (employeeId: string, employeePayRate2: EmployeePayRate2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('addNewRate', 'employeeId', employeeId)
            // verify required parameter 'employeePayRate2' is not null or undefined
            assertParamExists('addNewRate', 'employeePayRate2', employeePayRate2)
            const localVarPath = `/v1/employees/{employeeId}/payrates`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeePayRate2,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/payrates',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeePayRate2, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: View Employee Payrates
         * @summary Get Employee Payrates by EmployeeID
         * @param {string} employeeId ID of employee for which you want to get payrates
         * @param {string} [continuationToken] Token to get next set of payrates
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeId: async (employeeId: string, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getByEmployeeId', 'employeeId', employeeId)
            const localVarPath = `/v1/employees/{employeeId}/payrates`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/payrates',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: Update Employee PayRates
         * @summary Update Employee Payrate by EmployeeID
         * @param {string} employeeId ID of an Employee that has the Payrate you wish to update
         * @param {string} payrateId ID of the Payrate you wish to update
         * @param {EmployeePayRate3} employeePayRate3 EmployeePayRate with ID set and fields updated
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByEmployeeIdAndPayrateId: async (employeeId: string, payrateId: string, employeePayRate3: EmployeePayRate3, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('updateByEmployeeIdAndPayrateId', 'employeeId', employeeId)
            // verify required parameter 'payrateId' is not null or undefined
            assertParamExists('updateByEmployeeIdAndPayrateId', 'payrateId', payrateId)
            // verify required parameter 'employeePayRate3' is not null or undefined
            assertParamExists('updateByEmployeeIdAndPayrateId', 'employeePayRate3', employeePayRate3)
            const localVarPath = `/v1/employees/{employeeId}/payrates/{payrateId}`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)))
                .replace(`{${"payrateId"}}`, encodeURIComponent(String(payrateId !== undefined ? payrateId : `-payrateId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeePayRate3,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/payrates/{payrateId}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeePayRate3, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeePayRatesApi - functional programming interface
 * @export
 */
export const EmployeePayRatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeePayRatesApiAxiosParamCreator(configuration)
    return {
        /**
         * This immediately creates a new payrate related to an Employee in Paycor\'s system. There is no way to undo or reverse this operation.   Data Access: Create Employee PayRates Sequence numbers must be consecutive and unique
         * @summary Add Payrate to Employee
         * @param {EmployeePayRatesApiAddNewRateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addNewRate(requestParameters: EmployeePayRatesApiAddNewRateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const employeePayRate2: EmployeePayRate2 = {
                EffectiveStartDate: requestParameters.EffectiveStartDate,
                EffectiveEndDate: requestParameters.EffectiveEndDate,
                SequenceNumber: requestParameters.SequenceNumber,
                PayRate: requestParameters.PayRate,
                AnnualPayRate: requestParameters.AnnualPayRate,
                Description: requestParameters.Description,
                Type: requestParameters.Type,
                Reason: requestParameters.Reason,
                Notes: requestParameters.Notes
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addNewRate(requestParameters.employeeId, employeePayRate2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: View Employee Payrates
         * @summary Get Employee Payrates by EmployeeID
         * @param {EmployeePayRatesApiGetByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getByEmployeeId(requestParameters: EmployeePayRatesApiGetByEmployeeIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfEmployeePayRate>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getByEmployeeId(requestParameters.employeeId, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: Update Employee PayRates
         * @summary Update Employee Payrate by EmployeeID
         * @param {EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateByEmployeeIdAndPayrateId(requestParameters: EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const employeePayRate3: EmployeePayRate3 = {
                EffectiveStartDate: requestParameters.EffectiveStartDate,
                SequenceNumber: requestParameters.SequenceNumber,
                PayRate: requestParameters.PayRate,
                AnnualPayRate: requestParameters.AnnualPayRate,
                Description: requestParameters.Description,
                Type: requestParameters.Type,
                Reason: requestParameters.Reason,
                Notes: requestParameters.Notes
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateByEmployeeIdAndPayrateId(requestParameters.employeeId, requestParameters.payrateId, employeePayRate3, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeePayRatesApi - factory interface
 * @export
 */
export const EmployeePayRatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeePayRatesApiFp(configuration)
    return {
        /**
         * This immediately creates a new payrate related to an Employee in Paycor\'s system. There is no way to undo or reverse this operation.   Data Access: Create Employee PayRates Sequence numbers must be consecutive and unique
         * @summary Add Payrate to Employee
         * @param {EmployeePayRatesApiAddNewRateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addNewRate(requestParameters: EmployeePayRatesApiAddNewRateRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.addNewRate(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: View Employee Payrates
         * @summary Get Employee Payrates by EmployeeID
         * @param {EmployeePayRatesApiGetByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getByEmployeeId(requestParameters: EmployeePayRatesApiGetByEmployeeIdRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfEmployeePayRate> {
            return localVarFp.getByEmployeeId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: Update Employee PayRates
         * @summary Update Employee Payrate by EmployeeID
         * @param {EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateByEmployeeIdAndPayrateId(requestParameters: EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.updateByEmployeeIdAndPayrateId(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addNewRate operation in EmployeePayRatesApi.
 * @export
 * @interface EmployeePayRatesApiAddNewRateRequest
 */
export type EmployeePayRatesApiAddNewRateRequest = {
    
    /**
    * ID of the Employee you wish to create the payrate for
    * @type {string}
    * @memberof EmployeePayRatesApiAddNewRate
    */
    readonly employeeId: string
    
} & EmployeePayRate2

/**
 * Request parameters for getByEmployeeId operation in EmployeePayRatesApi.
 * @export
 * @interface EmployeePayRatesApiGetByEmployeeIdRequest
 */
export type EmployeePayRatesApiGetByEmployeeIdRequest = {
    
    /**
    * ID of employee for which you want to get payrates
    * @type {string}
    * @memberof EmployeePayRatesApiGetByEmployeeId
    */
    readonly employeeId: string
    
    /**
    * Token to get next set of payrates
    * @type {string}
    * @memberof EmployeePayRatesApiGetByEmployeeId
    */
    readonly continuationToken?: string
    
}

/**
 * Request parameters for updateByEmployeeIdAndPayrateId operation in EmployeePayRatesApi.
 * @export
 * @interface EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest
 */
export type EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest = {
    
    /**
    * ID of an Employee that has the Payrate you wish to update
    * @type {string}
    * @memberof EmployeePayRatesApiUpdateByEmployeeIdAndPayrateId
    */
    readonly employeeId: string
    
    /**
    * ID of the Payrate you wish to update
    * @type {string}
    * @memberof EmployeePayRatesApiUpdateByEmployeeIdAndPayrateId
    */
    readonly payrateId: string
    
} & EmployeePayRate3

/**
 * EmployeePayRatesApiGenerated - object-oriented interface
 * @export
 * @class EmployeePayRatesApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeePayRatesApiGenerated extends BaseAPI {
    /**
     * This immediately creates a new payrate related to an Employee in Paycor\'s system. There is no way to undo or reverse this operation.   Data Access: Create Employee PayRates Sequence numbers must be consecutive and unique
     * @summary Add Payrate to Employee
     * @param {EmployeePayRatesApiAddNewRateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayRatesApiGenerated
     */
    public addNewRate(requestParameters: EmployeePayRatesApiAddNewRateRequest, options?: AxiosRequestConfig) {
        return EmployeePayRatesApiFp(this.configuration).addNewRate(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: View Employee Payrates
     * @summary Get Employee Payrates by EmployeeID
     * @param {EmployeePayRatesApiGetByEmployeeIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayRatesApiGenerated
     */
    public getByEmployeeId(requestParameters: EmployeePayRatesApiGetByEmployeeIdRequest, options?: AxiosRequestConfig) {
        return EmployeePayRatesApiFp(this.configuration).getByEmployeeId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: Update Employee PayRates
     * @summary Update Employee Payrate by EmployeeID
     * @param {EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayRatesApiGenerated
     */
    public updateByEmployeeIdAndPayrateId(requestParameters: EmployeePayRatesApiUpdateByEmployeeIdAndPayrateIdRequest, options?: AxiosRequestConfig) {
        return EmployeePayRatesApiFp(this.configuration).updateByEmployeeIdAndPayrateId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
