/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PagedResultOfPayStubFile } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeDocumentsApi - axios parameter creator
 * @export
 */
export const EmployeeDocumentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Data Access: Download Employee Pay Stub Document
         * @summary Download Employee Pay Stub Document
         * @param {string} employeeId Id of an Employee for whom you want to get the Pay Stub Document
         * @param {string} documentId Id of Pay Stub Document
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadPayStub: async (employeeId: string, documentId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('downloadPayStub', 'employeeId', employeeId)
            // verify required parameter 'documentId' is not null or undefined
            assertParamExists('downloadPayStub', 'documentId', documentId)
            const localVarPath = `/v1/employees/{employeeId}/PayStubDocument/{documentId}`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)))
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId !== undefined ? documentId : `-documentId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/PayStubDocument/{documentId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start Date and End Date are required parameters.  Data Access: Get Employee Pay Stub Document Link
         * @summary Get Employee Pay Stubs document link by EmployeeID
         * @param {string} employeeId ID of an Employee for whom you want to get the Pay Stubs Document Link
         * @param {string} startDate Date that is earlier or equal to paycheck date
         * @param {string} endDate Date that is after or equal to paycheck date
         * @param {string} [continuationToken] Token to get the next set of Employee Pay Stubs Document Links
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayStubDocumentByEmployeeId: async (employeeId: string, startDate: string, endDate: string, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getPayStubDocumentByEmployeeId', 'employeeId', employeeId)
            // verify required parameter 'startDate' is not null or undefined
            assertParamExists('getPayStubDocumentByEmployeeId', 'startDate', startDate)
            // verify required parameter 'endDate' is not null or undefined
            assertParamExists('getPayStubDocumentByEmployeeId', 'endDate', endDate)
            const localVarPath = `/v1/employees/{employeeId}/paystubDocumentData`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString() :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString() :
                    endDate;
            }

            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/paystubDocumentData',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeDocumentsApi - functional programming interface
 * @export
 */
export const EmployeeDocumentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeDocumentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Data Access: Download Employee Pay Stub Document
         * @summary Download Employee Pay Stub Document
         * @param {EmployeeDocumentsApiDownloadPayStubRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadPayStub(requestParameters: EmployeeDocumentsApiDownloadPayStubRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Uint8Array | File | buffer.File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadPayStub(requestParameters.employeeId, requestParameters.documentId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Start Date and End Date are required parameters.  Data Access: Get Employee Pay Stub Document Link
         * @summary Get Employee Pay Stubs document link by EmployeeID
         * @param {EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayStubDocumentByEmployeeId(requestParameters: EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfPayStubFile>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayStubDocumentByEmployeeId(requestParameters.employeeId, requestParameters.startDate, requestParameters.endDate, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeDocumentsApi - factory interface
 * @export
 */
export const EmployeeDocumentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeDocumentsApiFp(configuration)
    return {
        /**
         * Data Access: Download Employee Pay Stub Document
         * @summary Download Employee Pay Stub Document
         * @param {EmployeeDocumentsApiDownloadPayStubRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadPayStub(requestParameters: EmployeeDocumentsApiDownloadPayStubRequest, options?: AxiosRequestConfig): AxiosPromise<Uint8Array | File | buffer.File> {
            return localVarFp.downloadPayStub(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Start Date and End Date are required parameters.  Data Access: Get Employee Pay Stub Document Link
         * @summary Get Employee Pay Stubs document link by EmployeeID
         * @param {EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayStubDocumentByEmployeeId(requestParameters: EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfPayStubFile> {
            return localVarFp.getPayStubDocumentByEmployeeId(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for downloadPayStub operation in EmployeeDocumentsApi.
 * @export
 * @interface EmployeeDocumentsApiDownloadPayStubRequest
 */
export type EmployeeDocumentsApiDownloadPayStubRequest = {
    
    /**
    * Id of an Employee for whom you want to get the Pay Stub Document
    * @type {string}
    * @memberof EmployeeDocumentsApiDownloadPayStub
    */
    readonly employeeId: string
    
    /**
    * Id of Pay Stub Document
    * @type {string}
    * @memberof EmployeeDocumentsApiDownloadPayStub
    */
    readonly documentId: string
    
}

/**
 * Request parameters for getPayStubDocumentByEmployeeId operation in EmployeeDocumentsApi.
 * @export
 * @interface EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest
 */
export type EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest = {
    
    /**
    * ID of an Employee for whom you want to get the Pay Stubs Document Link
    * @type {string}
    * @memberof EmployeeDocumentsApiGetPayStubDocumentByEmployeeId
    */
    readonly employeeId: string
    
    /**
    * Date that is earlier or equal to paycheck date
    * @type {string}
    * @memberof EmployeeDocumentsApiGetPayStubDocumentByEmployeeId
    */
    readonly startDate: string
    
    /**
    * Date that is after or equal to paycheck date
    * @type {string}
    * @memberof EmployeeDocumentsApiGetPayStubDocumentByEmployeeId
    */
    readonly endDate: string
    
    /**
    * Token to get the next set of Employee Pay Stubs Document Links
    * @type {string}
    * @memberof EmployeeDocumentsApiGetPayStubDocumentByEmployeeId
    */
    readonly continuationToken?: string
    
}

/**
 * EmployeeDocumentsApiGenerated - object-oriented interface
 * @export
 * @class EmployeeDocumentsApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeDocumentsApiGenerated extends BaseAPI {
    /**
     * Data Access: Download Employee Pay Stub Document
     * @summary Download Employee Pay Stub Document
     * @param {EmployeeDocumentsApiDownloadPayStubRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeDocumentsApiGenerated
     */
    public downloadPayStub(requestParameters: EmployeeDocumentsApiDownloadPayStubRequest, options?: AxiosRequestConfig) {
        return EmployeeDocumentsApiFp(this.configuration).downloadPayStub(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start Date and End Date are required parameters.  Data Access: Get Employee Pay Stub Document Link
     * @summary Get Employee Pay Stubs document link by EmployeeID
     * @param {EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeDocumentsApiGenerated
     */
    public getPayStubDocumentByEmployeeId(requestParameters: EmployeeDocumentsApiGetPayStubDocumentByEmployeeIdRequest, options?: AxiosRequestConfig) {
        return EmployeeDocumentsApiFp(this.configuration).getPayStubDocumentByEmployeeId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
