/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Includes8 } from '../models';
// @ts-ignore
import { PagedResultOfPayPeriod } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeePayScheduleApi - axios parameter creator
 * @export
 */
export const EmployeePayScheduleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This API will return upcoming pay scheduled for a given employee (upcoming check dates), or allow looking up the check date for specific pay period dates. * You must either specify the exact Period Start & End Date, or leave them blank.    * Alternatively you may consider \'GET Legal Entity Pay Schedule\' which takes a range parameter.   * You can look up pay period dates from \'GET Legal Entity Pay Schedule\' (scheduled dates) or \'GET Legal Entity Pay Data\' (actual dates) * The actual pay dates may change depending on when the client admin processes payroll.  Data Access: View Employee Pay Schedule
         * @summary Get Employee Pay Schedule by EmployeeID
         * @param {string} employeeId ID of the Employee for which you want to get the Pay Schedule
         * @param {string} [periodStartDate] Exact Period Start Date of Pay Schedule, to lookup specific payrun. 
         * @param {string} [periodEndDate] Exact Period End Date of Pay Schedule, if you wish to filter - defaults to showing upcoming (future) runs
         * @param {string} [continuationToken] Token to get the next set of Employee Pay Schedule
         * @param {Array<Includes8>} [include] Options to include more data: Additional Runs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUpcomingCheckDates: async (employeeId: string, periodStartDate?: string, periodEndDate?: string, continuationToken?: string, include?: Array<Includes8>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getUpcomingCheckDates', 'employeeId', employeeId)
            const localVarPath = `/v1/employees/{employeeId}/payschedule`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (periodStartDate !== undefined) {
                localVarQueryParameter['periodStartDate'] = (periodStartDate as any instanceof Date) ?
                    (periodStartDate as any).toISOString() :
                    periodStartDate;
            }

            if (periodEndDate !== undefined) {
                localVarQueryParameter['periodEndDate'] = (periodEndDate as any instanceof Date) ?
                    (periodEndDate as any).toISOString() :
                    periodEndDate;
            }

            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }

            if (include) {
                localVarQueryParameter['include'] = include;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/payschedule',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeePayScheduleApi - functional programming interface
 * @export
 */
export const EmployeePayScheduleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeePayScheduleApiAxiosParamCreator(configuration)
    return {
        /**
         * This API will return upcoming pay scheduled for a given employee (upcoming check dates), or allow looking up the check date for specific pay period dates. * You must either specify the exact Period Start & End Date, or leave them blank.    * Alternatively you may consider \'GET Legal Entity Pay Schedule\' which takes a range parameter.   * You can look up pay period dates from \'GET Legal Entity Pay Schedule\' (scheduled dates) or \'GET Legal Entity Pay Data\' (actual dates) * The actual pay dates may change depending on when the client admin processes payroll.  Data Access: View Employee Pay Schedule
         * @summary Get Employee Pay Schedule by EmployeeID
         * @param {EmployeePayScheduleApiGetUpcomingCheckDatesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUpcomingCheckDates(requestParameters: EmployeePayScheduleApiGetUpcomingCheckDatesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedResultOfPayPeriod>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUpcomingCheckDates(requestParameters.employeeId, requestParameters.periodStartDate, requestParameters.periodEndDate, requestParameters.continuationToken, requestParameters.include, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeePayScheduleApi - factory interface
 * @export
 */
export const EmployeePayScheduleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeePayScheduleApiFp(configuration)
    return {
        /**
         * This API will return upcoming pay scheduled for a given employee (upcoming check dates), or allow looking up the check date for specific pay period dates. * You must either specify the exact Period Start & End Date, or leave them blank.    * Alternatively you may consider \'GET Legal Entity Pay Schedule\' which takes a range parameter.   * You can look up pay period dates from \'GET Legal Entity Pay Schedule\' (scheduled dates) or \'GET Legal Entity Pay Data\' (actual dates) * The actual pay dates may change depending on when the client admin processes payroll.  Data Access: View Employee Pay Schedule
         * @summary Get Employee Pay Schedule by EmployeeID
         * @param {EmployeePayScheduleApiGetUpcomingCheckDatesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUpcomingCheckDates(requestParameters: EmployeePayScheduleApiGetUpcomingCheckDatesRequest, options?: AxiosRequestConfig): AxiosPromise<PagedResultOfPayPeriod> {
            return localVarFp.getUpcomingCheckDates(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getUpcomingCheckDates operation in EmployeePayScheduleApi.
 * @export
 * @interface EmployeePayScheduleApiGetUpcomingCheckDatesRequest
 */
export type EmployeePayScheduleApiGetUpcomingCheckDatesRequest = {
    
    /**
    * ID of the Employee for which you want to get the Pay Schedule
    * @type {string}
    * @memberof EmployeePayScheduleApiGetUpcomingCheckDates
    */
    readonly employeeId: string
    
    /**
    * Exact Period Start Date of Pay Schedule, to lookup specific payrun. 
    * @type {string}
    * @memberof EmployeePayScheduleApiGetUpcomingCheckDates
    */
    readonly periodStartDate?: string
    
    /**
    * Exact Period End Date of Pay Schedule, if you wish to filter - defaults to showing upcoming (future) runs
    * @type {string}
    * @memberof EmployeePayScheduleApiGetUpcomingCheckDates
    */
    readonly periodEndDate?: string
    
    /**
    * Token to get the next set of Employee Pay Schedule
    * @type {string}
    * @memberof EmployeePayScheduleApiGetUpcomingCheckDates
    */
    readonly continuationToken?: string
    
    /**
    * Options to include more data: Additional Runs
    * @type {Array<Includes8>}
    * @memberof EmployeePayScheduleApiGetUpcomingCheckDates
    */
    readonly include?: Array<Includes8>
    
}

/**
 * EmployeePayScheduleApiGenerated - object-oriented interface
 * @export
 * @class EmployeePayScheduleApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeePayScheduleApiGenerated extends BaseAPI {
    /**
     * This API will return upcoming pay scheduled for a given employee (upcoming check dates), or allow looking up the check date for specific pay period dates. * You must either specify the exact Period Start & End Date, or leave them blank.    * Alternatively you may consider \'GET Legal Entity Pay Schedule\' which takes a range parameter.   * You can look up pay period dates from \'GET Legal Entity Pay Schedule\' (scheduled dates) or \'GET Legal Entity Pay Data\' (actual dates) * The actual pay dates may change depending on when the client admin processes payroll.  Data Access: View Employee Pay Schedule
     * @summary Get Employee Pay Schedule by EmployeeID
     * @param {EmployeePayScheduleApiGetUpcomingCheckDatesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayScheduleApiGenerated
     */
    public getUpcomingCheckDates(requestParameters: EmployeePayScheduleApiGetUpcomingCheckDatesRequest, options?: AxiosRequestConfig) {
        return EmployeePayScheduleApiFp(this.configuration).getUpcomingCheckDates(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
