/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmployeeTimeCard2 } from '../models';
// @ts-ignore
import { ImportEmployee } from '../models';
// @ts-ignore
import { ImportPayrollHours } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
// @ts-ignore
import { TimeCardData } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeePayrollHoursApi - axios parameter creator
 * @export
 */
export const EmployeePayrollHoursApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Required parameters in body are: IntegrationVendor, ProcessId, LegalEntityId, EmployeeNumber, DepartmentCode, EarningCode, BusinessStartDate  Data Access: Import Employee Hours and Earnings to Paygrid
         * @summary Add Employee Hours And Earnings To Paygrid
         * @param {number} legalEntityId ID of the Legal Entity for which you want to set employee hours and earnings
         * @param {ImportPayrollHours} importPayrollHours 
         * @param {boolean} [replaceData] If \&quot;True\&quot; is passed for this query parameter and a matching ProcessID is passed, then the system will fully replace the entire record that was previously added.
         * @param {boolean} [appendData] If \&quot;True\&quot; is passed for this query parameter, then the system will NOT replace any record that was previously added.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addHoursAndEarningsToPaygrid: async (legalEntityId: number, importPayrollHours: ImportPayrollHours, replaceData?: boolean, appendData?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('addHoursAndEarningsToPaygrid', 'legalEntityId', legalEntityId)
            // verify required parameter 'importPayrollHours' is not null or undefined
            assertParamExists('addHoursAndEarningsToPaygrid', 'importPayrollHours', importPayrollHours)
            const localVarPath = `/v1/legalentities/{legalEntityId}/payrollhours`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (replaceData !== undefined) {
                localVarQueryParameter['replaceData'] = replaceData;
            }

            if (appendData !== undefined) {
                localVarQueryParameter['appendData'] = appendData;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: importPayrollHours,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalentities/{legalEntityId}/payrollhours',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(importPayrollHours, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Data Access: Import Payroll Hours to Employee
         * @summary Import Payroll Hours to Employee
         * @param {string} employeeId ID of an Employee for whom you want to add the payroll hours
         * @param {EmployeeTimeCard2} employeeTimeCard2 Employee Hours object
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importToEmployee: async (employeeId: string, employeeTimeCard2: EmployeeTimeCard2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('importToEmployee', 'employeeId', employeeId)
            // verify required parameter 'employeeTimeCard2' is not null or undefined
            assertParamExists('importToEmployee', 'employeeTimeCard2', employeeTimeCard2)
            const localVarPath = `/v1/employees/{employeeId}/payrollhours`
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: employeeTimeCard2,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/employees/{employeeId}/payrollhours',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(employeeTimeCard2, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeePayrollHoursApi - functional programming interface
 * @export
 */
export const EmployeePayrollHoursApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeePayrollHoursApiAxiosParamCreator(configuration)
    return {
        /**
         * Required parameters in body are: IntegrationVendor, ProcessId, LegalEntityId, EmployeeNumber, DepartmentCode, EarningCode, BusinessStartDate  Data Access: Import Employee Hours and Earnings to Paygrid
         * @summary Add Employee Hours And Earnings To Paygrid
         * @param {EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addHoursAndEarningsToPaygrid(requestParameters: EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const importPayrollHours: ImportPayrollHours = {
                IntegrationVendor: requestParameters.IntegrationVendor,
                ProcessId: requestParameters.ProcessId,
                ImportEmployees: requestParameters.ImportEmployees
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addHoursAndEarningsToPaygrid(requestParameters.legalEntityId, importPayrollHours, requestParameters.replaceData, requestParameters.appendData, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Data Access: Import Payroll Hours to Employee
         * @summary Import Payroll Hours to Employee
         * @param {EmployeePayrollHoursApiImportToEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async importToEmployee(requestParameters: EmployeePayrollHoursApiImportToEmployeeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const employeeTimeCard2: EmployeeTimeCard2 = {
                AppId: requestParameters.AppId,
                IntegrationVendor: requestParameters.IntegrationVendor,
                ProcessId: requestParameters.ProcessId,
                LegalEntityId: requestParameters.LegalEntityId,
                EmployeeNumber: requestParameters.EmployeeNumber,
                DepartmentCode: requestParameters.DepartmentCode,
                JobCode: requestParameters.JobCode,
                TimeCardData: requestParameters.TimeCardData
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.importToEmployee(requestParameters.employeeId, employeeTimeCard2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeePayrollHoursApi - factory interface
 * @export
 */
export const EmployeePayrollHoursApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeePayrollHoursApiFp(configuration)
    return {
        /**
         * Required parameters in body are: IntegrationVendor, ProcessId, LegalEntityId, EmployeeNumber, DepartmentCode, EarningCode, BusinessStartDate  Data Access: Import Employee Hours and Earnings to Paygrid
         * @summary Add Employee Hours And Earnings To Paygrid
         * @param {EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addHoursAndEarningsToPaygrid(requestParameters: EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.addHoursAndEarningsToPaygrid(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Data Access: Import Payroll Hours to Employee
         * @summary Import Payroll Hours to Employee
         * @param {EmployeePayrollHoursApiImportToEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        importToEmployee(requestParameters: EmployeePayrollHoursApiImportToEmployeeRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.importToEmployee(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addHoursAndEarningsToPaygrid operation in EmployeePayrollHoursApi.
 * @export
 * @interface EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest
 */
export type EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest = {
    
    /**
    * ID of the Legal Entity for which you want to set employee hours and earnings
    * @type {number}
    * @memberof EmployeePayrollHoursApiAddHoursAndEarningsToPaygrid
    */
    readonly legalEntityId: number
    
    /**
    * If \"True\" is passed for this query parameter and a matching ProcessID is passed, then the system will fully replace the entire record that was previously added.
    * @type {boolean}
    * @memberof EmployeePayrollHoursApiAddHoursAndEarningsToPaygrid
    */
    readonly replaceData?: boolean
    
    /**
    * If \"True\" is passed for this query parameter, then the system will NOT replace any record that was previously added.
    * @type {boolean}
    * @memberof EmployeePayrollHoursApiAddHoursAndEarningsToPaygrid
    */
    readonly appendData?: boolean
    
} & ImportPayrollHours

/**
 * Request parameters for importToEmployee operation in EmployeePayrollHoursApi.
 * @export
 * @interface EmployeePayrollHoursApiImportToEmployeeRequest
 */
export type EmployeePayrollHoursApiImportToEmployeeRequest = {
    
    /**
    * ID of an Employee for whom you want to add the payroll hours
    * @type {string}
    * @memberof EmployeePayrollHoursApiImportToEmployee
    */
    readonly employeeId: string
    
} & EmployeeTimeCard2

/**
 * EmployeePayrollHoursApiGenerated - object-oriented interface
 * @export
 * @class EmployeePayrollHoursApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeePayrollHoursApiGenerated extends BaseAPI {
    /**
     * Required parameters in body are: IntegrationVendor, ProcessId, LegalEntityId, EmployeeNumber, DepartmentCode, EarningCode, BusinessStartDate  Data Access: Import Employee Hours and Earnings to Paygrid
     * @summary Add Employee Hours And Earnings To Paygrid
     * @param {EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayrollHoursApiGenerated
     */
    public addHoursAndEarningsToPaygrid(requestParameters: EmployeePayrollHoursApiAddHoursAndEarningsToPaygridRequest, options?: AxiosRequestConfig) {
        return EmployeePayrollHoursApiFp(this.configuration).addHoursAndEarningsToPaygrid(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Data Access: Import Payroll Hours to Employee
     * @summary Import Payroll Hours to Employee
     * @param {EmployeePayrollHoursApiImportToEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeePayrollHoursApiGenerated
     */
    public importToEmployee(requestParameters: EmployeePayrollHoursApiImportToEmployeeRequest, options?: AxiosRequestConfig) {
        return EmployeePayrollHoursApiFp(this.configuration).importToEmployee(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
