/* tslint:disable */
/* eslint-disable */
/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateOrUpdateResponse } from '../models';
// @ts-ignore
import { LaborCode3 } from '../models';
// @ts-ignore
import { LaborCode4 } from '../models';
// @ts-ignore
import { LaborCode5 } from '../models';
// @ts-ignore
import { PaycorError } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * LaborCodesApi - axios parameter creator
 * @export
 */
export const LaborCodesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This immediately creates a new labor code related to a Legal Entity in Paycor\'s system. There is no way to undo or reverse this operation. * Required body attributes:     * LaborCategoryId     * Code     * LaborCodeName       To make this call you will need the Job Costing or Workforce Management Service.  Data Access: Create and Update Labor Codes
         * @summary Add Labor Code to Legal Entity
         * @param {number} legalEntityId ID of the Legal Entity for which you want to create Labor Code
         * @param {LaborCode3} laborCode3 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLaborCodeToLegalEntity: async (legalEntityId: number, laborCode3: LaborCode3, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('addLaborCodeToLegalEntity', 'legalEntityId', legalEntityId)
            // verify required parameter 'laborCode3' is not null or undefined
            assertParamExists('addLaborCodeToLegalEntity', 'laborCode3', laborCode3)
            const localVarPath = `/v1/legalentities/{legalEntityId}/laborcodes`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: laborCode3,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalentities/{legalEntityId}/laborcodes',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(laborCode3, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns list of all Labor Code items.  * Labor code is not active if effective start date is after current date or if effective end date is before current date.  To make this call you will need the Job Costing or Workforce Management Service.  Data Access: View Labor Codes by Legal Entity Id
         * @summary Get Labor Code By Legal Entity ID
         * @param {number} legalEntityId ID of the Legal Entity for which you want to get labor codes (also known as job codes)
         * @param {string} [continuationToken] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByLegalEntityId: async (legalEntityId: number, continuationToken?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('listByLegalEntityId', 'legalEntityId', legalEntityId)
            const localVarPath = `/v1/legalentities/{legalEntityId}/laborcodes`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })
            if (continuationToken !== undefined) {
                localVarQueryParameter['continuationToken'] = continuationToken;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalentities/{legalEntityId}/laborcodes',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This operation updates specified labor code in Paycor\'s system.  To make this call you will need the Job Costing or Workforce Management Service.  LaborCodeId is required.  Data Access: Create and Update Labor Codes
         * @summary Update Labor Code
         * @param {number} legalEntityId ID of the Legal Entity for which you want to update Labor Code
         * @param {LaborCode5} laborCode5 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpecifiedLaborCode: async (legalEntityId: number, laborCode5: LaborCode5, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'legalEntityId' is not null or undefined
            assertParamExists('updateSpecifiedLaborCode', 'legalEntityId', legalEntityId)
            // verify required parameter 'laborCode5' is not null or undefined
            assertParamExists('updateSpecifiedLaborCode', 'laborCode5', laborCode5)
            const localVarPath = `/v1/legalentities/{legalEntityId}/laborcodes`
                .replace(`{${"legalEntityId"}}`, encodeURIComponent(String(legalEntityId !== undefined ? legalEntityId : `-legalEntityId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access-Token required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "accessToken", configuration })
            // authentication Apim-Subscription-Key required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Ocp-Apim-Subscription-Key", keyParamName: "apimSubscriptionKey", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: laborCode5,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/legalentities/{legalEntityId}/laborcodes',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(laborCode5, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LaborCodesApi - functional programming interface
 * @export
 */
export const LaborCodesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LaborCodesApiAxiosParamCreator(configuration)
    return {
        /**
         * This immediately creates a new labor code related to a Legal Entity in Paycor\'s system. There is no way to undo or reverse this operation. * Required body attributes:     * LaborCategoryId     * Code     * LaborCodeName       To make this call you will need the Job Costing or Workforce Management Service.  Data Access: Create and Update Labor Codes
         * @summary Add Labor Code to Legal Entity
         * @param {LaborCodesApiAddLaborCodeToLegalEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLaborCodeToLegalEntity(requestParameters: LaborCodesApiAddLaborCodeToLegalEntityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const laborCode3: LaborCode3 = {
                LaborCategoryId: requestParameters.LaborCategoryId,
                LaborCodeName: requestParameters.LaborCodeName,
                Description: requestParameters.Description,
                Code: requestParameters.Code,
                EffectiveStartDate: requestParameters.EffectiveStartDate,
                EffectiveEndDate: requestParameters.EffectiveEndDate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLaborCodeToLegalEntity(requestParameters.legalEntityId, laborCode3, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns list of all Labor Code items.  * Labor code is not active if effective start date is after current date or if effective end date is before current date.  To make this call you will need the Job Costing or Workforce Management Service.  Data Access: View Labor Codes by Legal Entity Id
         * @summary Get Labor Code By Legal Entity ID
         * @param {LaborCodesApiListByLegalEntityIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listByLegalEntityId(requestParameters: LaborCodesApiListByLegalEntityIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LaborCode4>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listByLegalEntityId(requestParameters.legalEntityId, requestParameters.continuationToken, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This operation updates specified labor code in Paycor\'s system.  To make this call you will need the Job Costing or Workforce Management Service.  LaborCodeId is required.  Data Access: Create and Update Labor Codes
         * @summary Update Labor Code
         * @param {LaborCodesApiUpdateSpecifiedLaborCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSpecifiedLaborCode(requestParameters: LaborCodesApiUpdateSpecifiedLaborCodeRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateOrUpdateResponse>> {
            const laborCode5: LaborCode5 = {
                LaborCodeId: requestParameters.LaborCodeId,
                LaborCodeName: requestParameters.LaborCodeName,
                Description: requestParameters.Description,
                Code: requestParameters.Code,
                EffectiveStartDate: requestParameters.EffectiveStartDate,
                EffectiveEndDate: requestParameters.EffectiveEndDate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSpecifiedLaborCode(requestParameters.legalEntityId, laborCode5, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LaborCodesApi - factory interface
 * @export
 */
export const LaborCodesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LaborCodesApiFp(configuration)
    return {
        /**
         * This immediately creates a new labor code related to a Legal Entity in Paycor\'s system. There is no way to undo or reverse this operation. * Required body attributes:     * LaborCategoryId     * Code     * LaborCodeName       To make this call you will need the Job Costing or Workforce Management Service.  Data Access: Create and Update Labor Codes
         * @summary Add Labor Code to Legal Entity
         * @param {LaborCodesApiAddLaborCodeToLegalEntityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLaborCodeToLegalEntity(requestParameters: LaborCodesApiAddLaborCodeToLegalEntityRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.addLaborCodeToLegalEntity(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns list of all Labor Code items.  * Labor code is not active if effective start date is after current date or if effective end date is before current date.  To make this call you will need the Job Costing or Workforce Management Service.  Data Access: View Labor Codes by Legal Entity Id
         * @summary Get Labor Code By Legal Entity ID
         * @param {LaborCodesApiListByLegalEntityIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listByLegalEntityId(requestParameters: LaborCodesApiListByLegalEntityIdRequest, options?: AxiosRequestConfig): AxiosPromise<LaborCode4> {
            return localVarFp.listByLegalEntityId(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * This operation updates specified labor code in Paycor\'s system.  To make this call you will need the Job Costing or Workforce Management Service.  LaborCodeId is required.  Data Access: Create and Update Labor Codes
         * @summary Update Labor Code
         * @param {LaborCodesApiUpdateSpecifiedLaborCodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSpecifiedLaborCode(requestParameters: LaborCodesApiUpdateSpecifiedLaborCodeRequest, options?: AxiosRequestConfig): AxiosPromise<CreateOrUpdateResponse> {
            return localVarFp.updateSpecifiedLaborCode(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for addLaborCodeToLegalEntity operation in LaborCodesApi.
 * @export
 * @interface LaborCodesApiAddLaborCodeToLegalEntityRequest
 */
export type LaborCodesApiAddLaborCodeToLegalEntityRequest = {
    
    /**
    * ID of the Legal Entity for which you want to create Labor Code
    * @type {number}
    * @memberof LaborCodesApiAddLaborCodeToLegalEntity
    */
    readonly legalEntityId: number
    
} & LaborCode3

/**
 * Request parameters for listByLegalEntityId operation in LaborCodesApi.
 * @export
 * @interface LaborCodesApiListByLegalEntityIdRequest
 */
export type LaborCodesApiListByLegalEntityIdRequest = {
    
    /**
    * ID of the Legal Entity for which you want to get labor codes (also known as job codes)
    * @type {number}
    * @memberof LaborCodesApiListByLegalEntityId
    */
    readonly legalEntityId: number
    
    /**
    * 
    * @type {string}
    * @memberof LaborCodesApiListByLegalEntityId
    */
    readonly continuationToken?: string
    
}

/**
 * Request parameters for updateSpecifiedLaborCode operation in LaborCodesApi.
 * @export
 * @interface LaborCodesApiUpdateSpecifiedLaborCodeRequest
 */
export type LaborCodesApiUpdateSpecifiedLaborCodeRequest = {
    
    /**
    * ID of the Legal Entity for which you want to update Labor Code
    * @type {number}
    * @memberof LaborCodesApiUpdateSpecifiedLaborCode
    */
    readonly legalEntityId: number
    
} & LaborCode5

/**
 * LaborCodesApiGenerated - object-oriented interface
 * @export
 * @class LaborCodesApiGenerated
 * @extends {BaseAPI}
 */
export class LaborCodesApiGenerated extends BaseAPI {
    /**
     * This immediately creates a new labor code related to a Legal Entity in Paycor\'s system. There is no way to undo or reverse this operation. * Required body attributes:     * LaborCategoryId     * Code     * LaborCodeName       To make this call you will need the Job Costing or Workforce Management Service.  Data Access: Create and Update Labor Codes
     * @summary Add Labor Code to Legal Entity
     * @param {LaborCodesApiAddLaborCodeToLegalEntityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LaborCodesApiGenerated
     */
    public addLaborCodeToLegalEntity(requestParameters: LaborCodesApiAddLaborCodeToLegalEntityRequest, options?: AxiosRequestConfig) {
        return LaborCodesApiFp(this.configuration).addLaborCodeToLegalEntity(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns list of all Labor Code items.  * Labor code is not active if effective start date is after current date or if effective end date is before current date.  To make this call you will need the Job Costing or Workforce Management Service.  Data Access: View Labor Codes by Legal Entity Id
     * @summary Get Labor Code By Legal Entity ID
     * @param {LaborCodesApiListByLegalEntityIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LaborCodesApiGenerated
     */
    public listByLegalEntityId(requestParameters: LaborCodesApiListByLegalEntityIdRequest, options?: AxiosRequestConfig) {
        return LaborCodesApiFp(this.configuration).listByLegalEntityId(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This operation updates specified labor code in Paycor\'s system.  To make this call you will need the Job Costing or Workforce Management Service.  LaborCodeId is required.  Data Access: Create and Update Labor Codes
     * @summary Update Labor Code
     * @param {LaborCodesApiUpdateSpecifiedLaborCodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LaborCodesApiGenerated
     */
    public updateSpecifiedLaborCode(requestParameters: LaborCodesApiUpdateSpecifiedLaborCodeRequest, options?: AxiosRequestConfig) {
        return LaborCodesApiFp(this.configuration).updateSpecifiedLaborCode(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
