/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LaborCode } from './labor-code';

/**
 * Employee-specific Payroll Import row for a specific working date range. Includes all Pay-related info. 
 * @export
 * @interface ImportEarning
 */
export interface ImportEarning {
    /**
     * Department code that the Hours should be paid under. You can use GET Legal Entity Departments to retrieve valid Code values. 
     * @type {number}
     * @memberof ImportEarning
     */
    'DepartmentCode': number;
    /**
     * Employee\'s earning Code. You can retrieve via Get Employee Earnings endpoints.
     * @type {string}
     * @memberof ImportEarning
     */
    'EarningCode': string;
    /**
     * Number of hours that Employee worked.
     * @type {number}
     * @memberof ImportEarning
     */
    'EarningHours'?: number;
    /**
     * Dollar amount that Employee earned.
     * @type {number}
     * @memberof ImportEarning
     */
    'EarningAmount'?: number | null;
    /**
     * Dollar rate to assign to the earning. 
     * @type {number}
     * @memberof ImportEarning
     */
    'EarningRate'?: number | null;
    /**
     * Start date of TimeCard
     * @type {string}
     * @memberof ImportEarning
     */
    'BusinessStartDate': string;
    /**
     * End date of TimeCard
     * @type {string}
     * @memberof ImportEarning
     */
    'BusinessEndDate'?: string | null;
    /**
     * The date worked (associated with this earning).  Optional. May be used by clients who have Workweek calculation feature enabled or by specific partner integrations.
     * @type {string}
     * @memberof ImportEarning
     */
    'DateWorked'?: string | null;
    /**
     * Optional. This allows supplying Labor Codes tied to this earning, used for Job Costing and other functionality. 
     * @type {Array<LaborCode>}
     * @memberof ImportEarning
     */
    'LaborCodes'?: Array<LaborCode> | null;
    /**
     * Unique identifier of the pay group in Paycor\'s system. You can retrieve by calling \'Get Pay Groups by Legal Entity ID\'
     * @type {string}
     * @memberof ImportEarning
     */
    'PayGroupId': string;
    /**
     * Optional, defaults to 1.  Indicates which paycheck for this employee the earning will appear on (essentially a sort order for the particular Employee).  Use sequential values such as 1, 2, 3...
     * @type {number}
     * @memberof ImportEarning
     */
    'PayNumber'?: number | null;
    /**
     * Optional. This field allows passing in additional information used by specific partner integrations.
     * @type {string}
     * @memberof ImportEarning
     */
    'ClientDefinedValue'?: string | null;
}

