/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmploymentStatus } from './employment-status';

/**
 * 
 * @export
 * @interface JobCosting
 */
export interface JobCosting {
    /**
     * Id of the Legal Entity.
     * @type {string}
     * @memberof JobCosting
     */
    'LegalEntityId'?: string | null;
    /**
     * The paycheck date. Also referred to as Pay Date.
     * @type {string}
     * @memberof JobCosting
     */
    'CheckDate'?: string | null;
    /**
     * Description of department Synonymous with OrganizationDescription
     * @type {string}
     * @memberof JobCosting
     */
    'DepartmentDescription'?: string | null;
    /**
     * Numeric code of department  Synonymous with OrganizationCode
     * @type {number}
     * @memberof JobCosting
     */
    'DepartmentCode'?: number | null;
    /**
     * Labor category code 1
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory1Code'?: number | null;
    /**
     * Labor code 1
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode1'?: string | null;
    /**
     * Labor Code 1 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode1Id'?: string | null;
    /**
     * Description of labor category 1
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode1Description'?: string | null;
    /**
     * Labor category code 1
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory2Code'?: number | null;
    /**
     * Labor code 2
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode2'?: string | null;
    /**
     * Labor Code 2 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode2Id'?: string | null;
    /**
     * Description of labor category 1
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode2Description'?: string | null;
    /**
     * Labor category code 3
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory3Code'?: number | null;
    /**
     * Labor code 3
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode3'?: string | null;
    /**
     * Labor Code 3 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode3Id'?: string | null;
    /**
     * Description of labor category 3
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode3Description'?: string | null;
    /**
     * Labor category code 4
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory4Code'?: number | null;
    /**
     * Labor code 4
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode4'?: string | null;
    /**
     * Labor Code 4 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode4Id'?: string | null;
    /**
     * Description of labor category 4
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode4Description'?: string | null;
    /**
     * Labor category code 5
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory5Code'?: number | null;
    /**
     * Labor code 5
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode5'?: string | null;
    /**
     * Labor Code 5 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode5Id'?: string | null;
    /**
     * Description of labor category 5
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode5Description'?: string | null;
    /**
     * Labor category code 6
     * @type {number}
     * @memberof JobCosting
     */
    'LaborCategory6Code'?: number | null;
    /**
     * Labor code 6
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode6'?: string | null;
    /**
     * Labor Code 6 ID
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode6Id'?: string | null;
    /**
     * Description of labor category 6
     * @type {string}
     * @memberof JobCosting
     */
    'LaborCode6Description'?: string | null;
    /**
     * Account number 
     * @type {string}
     * @memberof JobCosting
     */
    'GLAccountNumber'?: string | null;
    /**
     * Account description 
     * @type {string}
     * @memberof JobCosting
     */
    'GLAccountDescription'?: string | null;
    /**
     * Credited amount
     * @type {number}
     * @memberof JobCosting
     */
    'CreditAmount'?: number | null;
    /**
     * Credited amount
     * @type {number}
     * @memberof JobCosting
     */
    'DebitAmount'?: number | null;
    /**
     * Week number
     * @type {number}
     * @memberof JobCosting
     */
    'WeekNumber'?: number;
    /**
     * Pay number
     * @type {number}
     * @memberof JobCosting
     */
    'PayNumber'?: number;
    /**
     * File Date Month
     * @type {number}
     * @memberof JobCosting
     */
    'FileDateMonth'?: number;
    /**
     * File date day
     * @type {number}
     * @memberof JobCosting
     */
    'FileDateDay'?: number;
    /**
     * File date year
     * @type {number}
     * @memberof JobCosting
     */
    'FileDateYear'?: number;
    /**
     * Unique identifier of the employee record in Paycor\'s system. Generated by Paycor.
     * @type {string}
     * @memberof JobCosting
     */
    'EmployeeId'?: string | null;
    /**
     * Employee\'s organization description
     * @type {string}
     * @memberof JobCosting
     */
    'EmployeeDepartmentDescription'?: string | null;
    /**
     * Employee\'s organization code
     * @type {number}
     * @memberof JobCosting
     */
    'EmployeeDepartmentCode'?: number | null;
    /**
     * Employee\'s last name
     * @type {string}
     * @memberof JobCosting
     */
    'EmployeeLastName'?: string | null;
    /**
     * Employee\'s first name
     * @type {string}
     * @memberof JobCosting
     */
    'EmployeeFirstName'?: string | null;
    /**
     * Employee\'s middle name
     * @type {string}
     * @memberof JobCosting
     */
    'EmployeeMiddleName'?: string | null;
    /**
     * Unique number of the employee in the tenant. Generated by Paycor.
     * @type {number}
     * @memberof JobCosting
     */
    'EmployeeNumber'?: number | null;
    /**
     * Enumeration of valid Employment Status values.             
     * @type {EmploymentStatus}
     * @memberof JobCosting
     */
    'EmployeeStatus'?: EmploymentStatus;
    /**
     * Check number.
     * @type {number}
     * @memberof JobCosting
     */
    'CheckNumber'?: number | null;
    /**
     * Period start date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
     * @type {string}
     * @memberof JobCosting
     */
    'PeriodStartDate'?: string;
    /**
     * Period end date. Format: YYYY-MM-DDTHH:MM:SSZ  (ISO-8601 standard)              
     * @type {string}
     * @memberof JobCosting
     */
    'PeriodEndDate'?: string;
}

