/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobDepartment } from './job-department';
import { JobLocation } from './job-location';
import { JobPayRange } from './job-pay-range';
import { JobPriority } from './job-priority';
import { JobRemoteStatus } from './job-remote-status';
import { JobStatus } from './job-status';
import { JobUser } from './job-user';

/**
 * Details about the Job.
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * Unique identifier of the Job in Paycor\'s system.
     * @type {string}
     * @memberof Job
     */
    'Id'?: string | null;
    /**
     * The ATS client ID.
     * @type {string}
     * @memberof Job
     */
    'ATSAccountId'?: string | null;
    /**
     * The job\'s human readable job number.
     * @type {string}
     * @memberof Job
     */
    'Number'?: string | null;
    /**
     * The job\'s name.
     * @type {string}
     * @memberof Job
     */
    'Title'?: string | null;
    /**
     * The job\'s description in HTML format.
     * @type {string}
     * @memberof Job
     */
    'Description'?: string | null;
    /**
     * 
     * @type {JobStatus}
     * @memberof Job
     */
    'Status'?: JobStatus;
    /**
     * The number of openings for the job.
     * @type {number}
     * @memberof Job
     */
    'Openings'?: number;
    /**
     * 
     * @type {JobPriority}
     * @memberof Job
     */
    'Priority'?: JobPriority;
    /**
     * If the job is confidential.
     * @type {boolean}
     * @memberof Job
     */
    'Confidential'?: boolean;
    /**
     * If the job is an internal only job.
     * @type {boolean}
     * @memberof Job
     */
    'Internal'?: boolean;
    /**
     * The targeted time to fill the job.
     * @type {number}
     * @memberof Job
     */
    'TimeToFill'?: number;
    /**
     * 
     * @type {JobRemoteStatus}
     * @memberof Job
     */
    'RemoteStatus'?: JobRemoteStatus;
    /**
     * The EEO (Equal Employment Opportunity) category specification for the job. Can be one of these values: Executive/Senior-Level Officials and Managers, First/Mid-Level Officials and Managers, Professionals, Technicians, Sales Workers, Administrative Support Workers, Craft Workers, Operatives, Laborers and Helpers, Service Workers.
     * @type {string}
     * @memberof Job
     */
    'EeoCategory'?: string | null;
    /**
     * 
     * @type {JobPayRange}
     * @memberof Job
     */
    'PayRange'?: JobPayRange;
    /**
     * 
     * @type {JobLocation}
     * @memberof Job
     */
    'ATSLocation'?: JobLocation;
    /**
     * 
     * @type {JobDepartment}
     * @memberof Job
     */
    'ATSDepartment'?: JobDepartment;
    /**
     * The hiring managers assigned to the job.
     * @type {Array<JobUser>}
     * @memberof Job
     */
    'HiringManagers'?: Array<JobUser> | null;
    /**
     * The recruiters assigned to the job.
     * @type {Array<JobUser>}
     * @memberof Job
     */
    'Recruiters'?: Array<JobUser> | null;
    /**
     * The team members assigned to the job.
     * @type {Array<JobUser>}
     * @memberof Job
     */
    'TeamMembers'?: Array<JobUser> | null;
    /**
     * The executives assigned to the job.
     * @type {Array<JobUser>}
     * @memberof Job
     */
    'Executives'?: Array<JobUser> | null;
    /**
     * The date when the job was activated.
     * @type {string}
     * @memberof Job
     */
    'ActivatedDate'?: string | null;
    /**
     * The date when the job was created.
     * @type {string}
     * @memberof Job
     */
    'CreatedDate'?: string;
    /**
     * The date when the job was last modified.
     * @type {string}
     * @memberof Job
     */
    'ModifiedDate'?: string;
    /**
     * Is the job posted to the company careers page.
     * @type {boolean}
     * @memberof Job
     */
    'PostedToCareers'?: boolean;
    /**
     * Is the job posted to the free Indeed feed.
     * @type {boolean}
     * @memberof Job
     */
    'PostedToIndeed'?: boolean;
    /**
     * Is the job posted to Smart Sourcing.
     * @type {boolean}
     * @memberof Job
     */
    'PostedToSmartSourcing'?: boolean;
    /**
     * Is the job posted to the free LinkedIn.
     * @type {boolean}
     * @memberof Job
     */
    'PostedToLinkedIn'?: boolean;
    /**
     * Is the job posted to the free ZipRecruiter feed.
     * @type {boolean}
     * @memberof Job
     */
    'PostedToZipRecruiter'?: boolean;
    /**
     * Is the job posted to Gravity.             
     * @type {boolean}
     * @memberof Job
     */
    'PostedToGravity'?: boolean;
}

