/*
Paycor Public API


Welcome to Paycor's Public API! This document is a reference for the APIs Paycor has available, and acts as a complement to the \"Guides\" section. 

# Getting Started

<strong>To learn more about getting started with Paycor's Public APIs, check out our <a href=\"/guides\">Guides.</a></strong>

# GET, PUT, POST

* When requesting object, use GET endpoints. All list endpoints support paging, as described [in the other doc]. 
* When creating an object, use POST endpoints. Your code will need to create an object and send it to Paycor in your API call request body as JSON. You can use the \"request sample\" body as a starting point. Our endpoints will return a reference to the created object (the ID and GET API URL) for your system.
* When updating an object, you will use PUT endpoints. The general flow would be to: GET the object you want to update, modify the fields as desired, then PUT the object (as JSON in the request body) to our endpoints. Some fields like the object's ID cannot be updated because they are system-set.'


# Error Handling

* 400: Please consult the response text to correct your request information. 
* 401 with response \"Access denied due to missing subscription key\": Please include your APIM Subscription Key as header Ocp-Apim-Subscription-Key or querystring parameter subscription-key. 
* 401 with no response: Please ensure you included a valid & current Access Token in the Authorization header.
* 403: Please ensure your Access Token's scope has all the relevant access you need, on the AppCreator Data Access screen. 
* 404: Please validate the API route you are using. If that is correct, one of your IDs most likely does not exist or is not in a valid state. 
* 429: Paycor implements rate limits for our Public API. Each customer (implemented via APIM subscription key) has a limited number of calls. The number of calls is counted across all APIs, not per individual API. Please use bulk endpoints where available and spread your calls over a wider timespan.
  * The default rate limit is up to 1000 API calls per minute (total across all our Public APIs). 
* 500: Please contact Paycor. When you make a POST or PUT call and receive a 500, please do not retry the call automatically - this may result in double-posting. GETs can be safely retried.


# IDs

* ClientId = LegalEntityId
* TenantId = CompanyId
* EmployeeId is not visible in Paycor's UI, you must retrieve it from the Public API

# Earnings, Deductions, Taxes

This section describes the domain model for Paycor's Earnings, Deductions, and Taxes. This will provide background for many paydata-related Public API endpoints. 

Paycor stores Earnings, Deductions, and Taxes each at three levels:
* Global: Same data across all legal entities. Setup by Paycor for customers to choose from. Sample Codes (note these will not be setup on every Legal Entity):
  * Earnings: REG, OT
  * Taxes: FITWH, SOC, SOCER, OHCIN
  * Deductions: 401k, KMat, H125, UWay
* Legal Entity or Tenant: Codes setup &amp; customized on the legal entity or Tenant level. Must be tied to a Global Code. 
  * Perform UI allows creating Deduction and Earning codes on Tenant level (under Configure Company nav menu). These will be returned by the Legal Entity Public API endpoints. 
* Employee: codes setup on a particular employee, tied to a Legal Entity-level or Tenant-level code
  * Employee Earnings/Deductions/Taxes are applied during payroll. Many properties are inherited from the Legal Entity or Global levels, but some can be overridden. 

# Authentication

<!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OnboardingEmployee
 */
export interface OnboardingEmployee {
    /**
     * Id of the employee in the onboarding state.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'OnboardingEmployeeId'?: string;
    /**
     * Unique number of the employee.             
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'EmployeeNumber'?: number | null;
    /**
     * Id of the legal entity.
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'LegalEntityId'?: number;
    /**
     * First name of the employee in the onboarding state.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'FirstName'?: string | null;
    /**
     * Last name of the employee in the onboarding state.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'LastName'?: string | null;
    /**
     * First and last name of the employee in the onboarding state combined.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'FullName'?: string | null;
    /**
     * Email address of the employee in the onboarding state.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'EmailAddress'?: string | null;
    /**
     * Date when employee was invited.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'InvitedDate'?: string | null;
    /**
     * Indicates if this is invited or manual hiring.
     * @type {boolean}
     * @memberof OnboardingEmployee
     */
    'HasOnboardingAccess'?: boolean;
    /**
     * Date when the employee was hired.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'HireDate'?: string | null;
    /**
     * Number of the total steps in the onboarding.
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'StepsTotal'?: number | null;
    /**
     * Number of the completed steps in the onboarding.
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'StepsCompleted'?: number | null;
    /**
     * Last step that was completed by the employee.
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'LastEmployeeStepCompleted'?: number;
    /**
     * Date when the last step was completed by employee.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'LastEmployeeStepCompletedDate'?: string | null;
    /**
     * Last step that was completed by the admin.
     * @type {number}
     * @memberof OnboardingEmployee
     */
    'LastAdminStepCompleted'?: number | null;
    /**
     * Date when the last step was completed by admin. 
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'LastAdminStepCompletedDate'?: string | null;
    /**
     * Name of the work location.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'WorkLocation'?: string | null;
    /**
     * Id of the work location.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'WorkLocationId'?: string | null;
    /**
     * Full name of the employees manager.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'Manager'?: string | null;
    /**
     * Id of the employees manager.
     * @type {string}
     * @memberof OnboardingEmployee
     */
    'ManagerId'?: string | null;
}

